basePath: /api/v1
definitions:
  model.Community:
    properties:
      community_id:
        example: "0"
        type: string
      community_name:
        type: string
      create_time:
        type: string
      id:
        example: "0"
        type: string
      introduction:
        type: string
      update_time:
        type: string
    required:
    - community_name
    type: object
  model.Post:
    properties:
      community_id:
        example: "0"
        type: string
      content:
        type: string
      create_time:
        type: string
      id:
        example: "0"
        type: string
      post_id:
        example: "0"
        type: string
      status:
        description: 默认未通过审核
        type: integer
      title:
        type: string
      update_time:
        type: string
      user_id:
        example: "0"
        type: string
    required:
    - community_id
    - content
    - title
    type: object
  model.ReqPost:
    properties:
      community_id:
        example: "0"
        type: string
      content:
        type: string
      title:
        type: string
    type: object
  model.ResCommunity:
    properties:
      community_id:
        example: "0"
        type: string
      community_name:
        type: string
    type: object
  model.ResPost:
    properties:
      community_id:
        example: "0"
        type: string
      community_name:
        type: string
      content:
        type: string
      create_time:
        type: string
      id:
        example: "0"
        type: string
      introduction:
        type: string
      post_id:
        example: "0"
        type: string
      status:
        description: 默认未通过审核
        type: integer
      title:
        type: string
      update_time:
        type: string
      user_id:
        example: "0"
        type: string
      user_name:
        type: string
      vote_score:
        type: number
    required:
    - community_id
    - community_name
    - content
    - title
    type: object
  model.ResRegister:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
  tool.ResJson:
    properties:
      code:
        type: integer
      data: {}
      msg: {}
    type: object
host: 127.0.0.1:8085
info:
  contact:
    name: cold bin
    url: https://github.com/liuhaibin123456789/web-app.git
  description: 投票帖子网站后端接口
  title: web_app项目接口文档
  version: "1.0"
paths:
  /community:
    get:
      description: 获取前十个标签的id及名字，没有十个则返回所有
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/tool.ResJson'
            - properties:
                msg:
                  type: string
              type: object
      security:
      - CoreAPI: []
      summary: 获取社区分类信息
      tags:
      - community
    post:
      consumes:
      - application/json
      parameters:
      - description: 分类名
        in: body
        maxLength: 128
        minLength: 1
        name: community_name
        required: true
        schema:
          type: string
      - description: 介绍
        in: body
        maxLength: 256
        name: introduction
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/tool.ResJson'
            - properties:
                msg:
                  type: string
              type: object
      security:
      - CoreAPI: []
      summary: 创建社区分类
      tags:
      - community
  /community/{community_id}:
    get:
      description: 获取单个分类信息数据
      parameters:
      - description: 查询帖子的community_id
        in: path
        name: community_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/tool.ResJson'
            - properties:
                msg:
                  type: string
              type: object
      security:
      - CoreAPI: []
      summary: 获取社区分类详细信息
      tags:
      - community
  /login:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: 手机号
        in: formData
        maxLength: 11
        minLength: 11
        name: phone
        required: true
        type: string
      - description: 密码
        in: formData
        maxLength: 16
        minLength: 8
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/tool.ResJson'
      summary: 登录
      tags:
      - user
  /post:
    post:
      consumes:
      - application/json
      parameters:
      - description: 帖子json数据
        in: body
        name: post
        required: true
        schema:
          $ref: '#/definitions/model.ReqPost'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/tool.ResJson'
            - properties:
                msg:
                  type: string
              type: object
      security:
      - CoreAPI: []
      summary: 创建帖子
      tags:
      - post
  /post/{post_id}:
    get:
      parameters:
      - description: 查询帖子的post_id
        in: path
        name: post_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/tool.ResJson'
            - properties:
                msg:
                  type: string
              type: object
      security:
      - CoreAPI: []
      summary: 获取帖子详情
      tags:
      - post
  /post2:
    get:
      description: 支持时间和投票分数排序和查找社区分类下的帖子
      parameters:
      - description: 查询的页码
        in: query
        name: page
        type: string
      - description: 查询的单页数据
        in: query
        name: size
        type: string
      - description: '只有两个值：`time`表示结果按照时间排序返回；`score`表示结果按照分数排序返回 '
        in: query
        name: order
        type: string
      - description: 为空表示默认不按照社区分类查询；不为空，将按照所给id对应社区分类的帖子返回
        in: query
        name: community_id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/tool.ResJson'
            - properties:
                msg:
                  type: string
              type: object
      security:
      - CoreAPI: []
      summary: 获取帖子列表
      tags:
      - post
  /register:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: 手机号
        in: formData
        maxLength: 11
        minLength: 11
        name: phone
        required: true
        type: string
      - description: 密码
        in: formData
        maxLength: 16
        minLength: 8
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/tool.ResJson'
      summary: 注册
      tags:
      - user
  /tokens:
    post:
      consumes:
      - multipart/form-data
      description: 该api只在access_token失效时使用，并且请求头携带好refresh_token
      parameters:
      - description: header auth
        in: header
        name: Authorization
        required: true
        type: string
      - description: 用户user_id
        in: formData
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/tool.ResJson'
      summary: 获取token
      tags:
      - user
  /vote:
    post:
      consumes:
      - application/json
      parameters:
      - description: 投票帖子post_id
        in: body
        name: post_id
        required: true
        schema:
          type: string
      - description: 投票帖子，1表示投票赞成，-1表示反对，0表示不投票或取消投票
        in: body
        maxLength: 1
        name: direction
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/tool.ResJson'
            - properties:
                msg:
                  type: string
              type: object
      security:
      - CoreAPI: []
      summary: 帖子投票
      tags:
      - post
securityDefinitions:
  CoreAPI:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
